"""initial schema

Revision ID: 0083a26ae0b0
Revises:
Create Date: 2026-07-18 15:46:31.843653

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0083a26ae0b0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drift_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("feature_version", sa.String(length=32), nullable=False),
        sa.Column("metric_name", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("drifted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drift_metrics")),
    )
    op.create_index(op.f("ix_drift_metrics_date"), "drift_metrics", ["date"], unique=False)
    op.create_table(
        "features",
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("feature_version", sa.String(length=32), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("ticker", "date", "feature_version", name=op.f("pk_features")),
    )
    op.create_index("ix_features_date", "features", ["date"], unique=False)
    op.create_table(
        "model_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_type", sa.String(length=16), nullable=False),
        sa.Column("mlflow_run_id", sa.String(length=64), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_runs")),
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("equity", sa.Float(), nullable=False),
        sa.Column("daily_return", sa.Float(), nullable=False),
        sa.Column("gross_exposure", sa.Float(), nullable=False),
        sa.Column("net_exposure", sa.Float(), nullable=False),
        sa.Column("turnover", sa.Float(), nullable=False),
        sa.Column("positions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("date", name=op.f("pk_portfolio_snapshots")),
    )
    op.create_table(
        "predictions",
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("ticker", "date", "model_version", name=op.f("pk_predictions")),
    )
    op.create_index("ix_predictions_date", "predictions", ["date"], unique=False)
    op.create_table(
        "universe",
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("asset_type", sa.String(length=8), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "asset_type IN ('stock', 'etf')", name=op.f("ck_universe_asset_type_valid")
        ),
        sa.PrimaryKeyConstraint("ticker", name=op.f("pk_universe")),
    )
    op.create_table(
        "prices",
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "close > 0 AND open > 0 AND high > 0 AND low > 0",
            name=op.f("ck_prices_prices_positive"),
        ),
        sa.CheckConstraint("high >= low", name=op.f("ck_prices_high_gte_low")),
        sa.ForeignKeyConstraint(
            ["ticker"],
            ["universe.ticker"],
            name=op.f("fk_prices_ticker_universe"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("ticker", "date", name=op.f("pk_prices")),
    )
    op.create_index("ix_prices_date", "prices", ["date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prices_date", table_name="prices")
    op.drop_table("prices")
    op.drop_table("universe")
    op.drop_index("ix_predictions_date", table_name="predictions")
    op.drop_table("predictions")
    op.drop_table("portfolio_snapshots")
    op.drop_table("model_runs")
    op.drop_index("ix_features_date", table_name="features")
    op.drop_table("features")
    op.drop_index(op.f("ix_drift_metrics_date"), table_name="drift_metrics")
    op.drop_table("drift_metrics")
    # ### end Alembic commands ###
