"""pipeline alerts table

Moves the failure-alert log out of a JSONL file under DAGSTER_HOME and into the database.
The daemon records alerts and the API serves them from a different container; the file was
in neither a shared volume nor a persistent one, so `/alerts` could never read it and
`compose up` erased it. Postgres is what both containers already share.

Revision ID: 3de6e54eece0
Revises: d5a2c9f18e63
Create Date: 2026-07-28 08:11:49.436277

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3de6e54eece0"
down_revision: str | None = "d5a2c9f18e63"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_name", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_alerts")),
    )
    op.create_index(
        op.f("ix_pipeline_alerts_created_at"), "pipeline_alerts", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipeline_alerts_created_at"), table_name="pipeline_alerts")
    op.drop_table("pipeline_alerts")
    # ### end Alembic commands ###
