"""add option_quotes

Revision ID: 80ed0da02bb9
Revises: 0083a26ae0b0
Create Date: 2026-07-20 18:09:49.733576

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "80ed0da02bb9"
down_revision: str | None = "0083a26ae0b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "option_quotes",
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("strike", sa.Float(), nullable=False),
        sa.Column("option_type", sa.String(length=4), nullable=False),
        sa.Column("underlying_close", sa.Float(), nullable=False),
        sa.Column("bid", sa.Float(), nullable=True),
        sa.Column("ask", sa.Float(), nullable=True),
        sa.Column("last_price", sa.Float(), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("open_interest", sa.BigInteger(), nullable=False),
        sa.Column("implied_volatility", sa.Float(), nullable=False),
        sa.Column("in_the_money", sa.Boolean(), nullable=False),
        sa.Column("theo_value", sa.Float(), nullable=False),
        sa.Column("delta", sa.Float(), nullable=False),
        sa.Column("gamma", sa.Float(), nullable=False),
        sa.Column("theta", sa.Float(), nullable=False),
        sa.Column("vega", sa.Float(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "option_type IN ('call', 'put')", name=op.f("ck_option_quotes_option_type_valid")
        ),
        sa.PrimaryKeyConstraint(
            "snapshot_date",
            "ticker",
            "expiry",
            "strike",
            "option_type",
            name=op.f("pk_option_quotes"),
        ),
    )
    op.create_index(
        "ix_option_quotes_ticker_date", "option_quotes", ["ticker", "snapshot_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_option_quotes_ticker_date", table_name="option_quotes")
    op.drop_table("option_quotes")
    # ### end Alembic commands ###
